In [2]:
import pandas as pd
import numpy as np

In [4]:
a = pd.read_csv("./NB_Classifier.csv")
print(a)

   X  Y  Target
0  2  2       0
1  1  2       0
2  3  4       0
3  1  1       0
4  3  3       0
5  7  2       1
6  6  2       1
7  7  1       1
8  8  0       1
9  7  3       1


In [5]:
b = np.array(a)
print(b)
#separation of dataset w.r.t. their targets
c=[]
d=[]
for i in range(len(b)):
    if (b[i,-1] == 0):
        c.append(b[i,:-1])
    else:
        d.append(b[i,:-1])
print(c)
print(d)

[[2 2 0]
 [1 2 0]
 [3 4 0]
 [1 1 0]
 [3 3 0]
 [7 2 1]
 [6 2 1]
 [7 1 1]
 [8 0 1]
 [7 3 1]]
[array([2, 2], dtype=int64), array([1, 2], dtype=int64), array([3, 4], dtype=int64), array([1, 1], dtype=int64), array([3, 3], dtype=int64)]
[array([7, 2], dtype=int64), array([6, 2], dtype=int64), array([7, 1], dtype=int64), array([8, 0], dtype=int64), array([7, 3], dtype=int64)]


In [6]:
#Compute mean µ1 & µ2
mo=[]
m1=[]
m0=sum(c)/len(c)
m1=sum(d)/len(d)
print(m0)
print(m1)

[2.  2.4]
[7.  1.6]


In [8]:
#compute variance σ2
e=[]
f=[]
for i in range(len(c)):
   e.append(c[i]-m0)
   f.append(d[i]-m1)
print(e)
print(f)
e=np.square(e)
f=np.square(f)
print(e)
print(f)
variance_x = []
variance_y = []
variance_x = sum(e)/len(c)
variance_y = sum(f)/len(d)
print(variance_x)
print(variance_y) 

[array([ 0. , -0.4]), array([-1. , -0.4]), array([1. , 1.6]), array([-1. , -1.4]), array([1. , 0.6])]
[array([0. , 0.4]), array([-1. ,  0.4]), array([ 0. , -0.6]), array([ 1. , -1.6]), array([0. , 1.4])]
[[0.   0.16]
 [1.   0.16]
 [1.   2.56]
 [1.   1.96]
 [1.   0.36]]
[[0.   0.16]
 [1.   0.16]
 [0.   0.36]
 [1.   2.56]
 [0.   1.96]]
[0.8  1.04]
[0.4  1.04]


In [29]:
#Test data
t=c[3]
#gpdf for 0
g11 = 1/(2*3.14*variance_x)**.5
g12 = ((t-m0)**2)/(2*variance_x)
g13 = g1*np.exp(-g2)
print(g3)
#gpdf for 1
g21 = 1/(2*3.14*variance_y)**.5
g22 = ((t-m0)**2)/(2*variance_y)
g23 = g21*np.exp(-g22)
print(g23)
g31 = np.product(g13)
g41 = np.product(g23)
print(g31)
print(g41)
 

[0.03129720667070614, 0.03129720667070614, 0.03129720667070614, 0.03129720667070614, 0.03129720667070614]
[0.12782243 0.1738746 ]
0.03129720667070614
0.022225075034139823


In [28]:
if(g31>g41):
    print("Prediction = 0.0")
else:
    print("Prediction = 1")

Prediction = 0.0
